# inventory/forms.py
from django import forms
from django.utils import timezone

from .models import Category, Supplier, Product, StockMovement


# =====================================================================
# Styling mixin — Tailwind
# =====================================================================
class TailwindMixin:
    INPUT = "input"
    CHECKBOX = (
        "h-4 w-4 rounded border-slate-300 text-brand-600 "
        "focus:ring-brand-500 dark:border-slate-600 dark:bg-slate-800"
    )
    TEXTAREA = "input min-h-[80px]"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, field in self.fields.items():
            widget = field.widget

            if isinstance(widget, forms.CheckboxInput):
                css = self.CHECKBOX
            elif isinstance(widget, forms.Textarea):
                css = self.TEXTAREA
            else:
                css = self.INPUT

            existing = widget.attrs.get("class", "")
            widget.attrs["class"] = f"{existing} {css}".strip()

            if name in self.errors:
                widget.attrs["aria-invalid"] = "true"

            if field.required and not isinstance(widget, forms.CheckboxInput):
                widget.attrs.setdefault("aria-required", "true")


# =====================================================================
# Category
# =====================================================================
class CategoryForm(TailwindMixin, forms.ModelForm):
    class Meta:
        model = Category
        fields = ["name", "kind", "description", "is_controlled"]
        widgets = {
            "description": forms.Textarea(attrs={"rows": 3}),
        }

    def __init__(self, *args, business=None, **kwargs):
        self.business = business
        super().__init__(*args, **kwargs)
        self.fields["is_controlled"].required = False
        self.fields["description"].required = False

    def clean_name(self):
        name = (self.cleaned_data.get("name") or "").strip()
        if not name:
            raise forms.ValidationError("Name is required.")
        if self.business:
            qs = Category.objects.filter(business=self.business, name__iexact=name)
            if self.instance.pk:
                qs = qs.exclude(pk=self.instance.pk)
            if qs.exists():
                raise forms.ValidationError(
                    "A category with this name already exists."
                )
        return name


# =====================================================================
# Supplier
# =====================================================================
class SupplierForm(TailwindMixin, forms.ModelForm):
    class Meta:
        model = Supplier
        fields = [
            "name", "contact_person", "phone", "email",
            "address", "license_number", "tax_id", "is_active",
        ]
        widgets = {
            "address": forms.Textarea(attrs={"rows": 3}),
        }

    def __init__(self, *args, business=None, **kwargs):
        self.business = business
        super().__init__(*args, **kwargs)
        for name in ("is_active", "license_number", "tax_id"):
            self.fields[name].required = False

    def clean_name(self):
        name = (self.cleaned_data.get("name") or "").strip()
        if not name:
            raise forms.ValidationError("Name is required.")
        if self.business:
            qs = Supplier.objects.filter(business=self.business, name__iexact=name)
            if self.instance.pk:
                qs = qs.exclude(pk=self.instance.pk)
            if qs.exists():
                raise forms.ValidationError(
                    "A supplier with this name already exists."
                )
        return name

    def clean_email(self):
        return (self.cleaned_data.get("email") or "").strip().lower()

    def clean_license_number(self):
        return (self.cleaned_data.get("license_number") or "").strip()

    def clean_tax_id(self):
        return (self.cleaned_data.get("tax_id") or "").strip()


# =====================================================================
# Product
# =====================================================================
class ProductForm(TailwindMixin, forms.ModelForm):
    class Meta:
        model = Product
        # FIX: only real fields. `sku` and `barcode` are read-only here
        # because they're auto-generated by Product.save().
        fields = [
            # Naming
            "name", "strength", "form",
            # Classification
            "category", "supplier", "is_medicine",
            # Media
            "image",
            # Pricing
            "cost_price", "selling_price",
            # Pack
            "pack_size", "unit",
            # Medicine flags
            "is_prescription", "is_controlled",
            # Stock
            "quantity", "reorder_level", "expiry_date", "is_active",
        ]
        widgets = {
            "expiry_date": forms.DateInput(attrs={"type": "date"}),
        }

    # ---- Field groupings for the template ----
    NAMING_FIELDS = ("name", "strength", "form")
    CLASSIFICATION_FIELDS = ("category", "supplier", "is_medicine")
    PRICING_FIELDS = ("cost_price", "selling_price")
    PACK_FIELDS = ("pack_size", "unit")
    FLAG_FIELDS = ("is_prescription", "is_controlled")
    STOCK_FIELDS = ("quantity", "reorder_level", "expiry_date")
    STATUS_FIELDS = ("is_active",)

    def naming_fields(self):
        return [self[n] for n in self.NAMING_FIELDS if n in self.fields]

    def classification_fields(self):
        return [self[n] for n in self.CLASSIFICATION_FIELDS if n in self.fields]

    def pricing_fields(self):
        return [self[n] for n in self.PRICING_FIELDS if n in self.fields]

    def pack_fields(self):
        return [self[n] for n in self.PACK_FIELDS if n in self.fields]

    def flag_fields(self):
        return [self[n] for n in self.FLAG_FIELDS if n in self.fields]

    def stock_fields(self):
        return [self[n] for n in self.STOCK_FIELDS if n in self.fields]

    def status_fields(self):
        return [self[n] for n in self.STATUS_FIELDS if n in self.fields]

    # ---- Init ----
    def __init__(self, *args, business=None, **kwargs):
        self.business = business
        super().__init__(*args, **kwargs)

        if business:
            self.fields["category"].queryset = (
                business.categories.all().order_by("kind", "name")
            )
            self.fields["supplier"].queryset = (
                business.suppliers.filter(is_active=True)
            )

        self.fields["category"].empty_label = "— Select category —"
        self.fields["supplier"].empty_label = "— Select supplier —"

        # Optional fields
        for name in ("category", "supplier", "strength", "expiry_date"):
            self.fields[name].required = False

        # Boolean flags
        for name in ("is_medicine", "is_prescription",
                     "is_controlled", "is_active"):
            self.fields[name].required = False

        # Defaults on create
        if not self.instance.pk:
            self.fields["is_medicine"].initial = True
            self.fields["is_active"].initial = True
            self.fields["pack_size"].initial = 1

    # ---- Validation ----
    def clean_name(self):
        return (self.cleaned_data.get("name") or "").strip()

    def clean_strength(self):
        return (self.cleaned_data.get("strength") or "").strip()

    def clean(self):
        cleaned = super().clean()

        # Price sanity
        cost = cleaned.get("cost_price")
        sell = cleaned.get("selling_price")
        if cost is not None and sell is not None and sell < cost:
            self.add_error(
                "selling_price",
                "Selling price should not be below cost price.",
            )

        # Non-medicine products shouldn't be prescription or controlled
        is_medicine = cleaned.get("is_medicine")
        if not is_medicine:
            if cleaned.get("is_prescription"):
                self.add_error(
                    "is_prescription",
                    "Only medicines can be prescription-only.",
                )
            if cleaned.get("is_controlled"):
                self.add_error(
                    "is_controlled",
                    "Only medicines can be controlled substances.",
                )

        # Expiry date sanity
        expiry = cleaned.get("expiry_date")
        if expiry and expiry < timezone.localdate():
            self.add_error(
                "expiry_date",
                "Expiry date cannot be in the past.",
            )

        return cleaned


# =====================================================================
# Stock adjustment
# =====================================================================
class StockAdjustForm(TailwindMixin, forms.Form):
    """
    Stock adjustment form.

    Mode choices come from `StockMovement.MovementType` plus the
    special "set" (absolute stock count) mode handled by services.py.
    """

    # Build choices dynamically so this always matches the model
    MODE_CHOICES = [
        (StockMovement.MovementType.IN,        "Received (add stock)"),
        (StockMovement.MovementType.OUT,       "Dispensed (sold / issued)"),
        (StockMovement.MovementType.ADJUST,    "Adjustment (loss / damage)"),
        (StockMovement.MovementType.EXPIRED,   "Expired / disposed"),
        (StockMovement.MovementType.RETURN,    "Return to supplier"),
        ("set",                                "Set exact quantity (stock count)"),
    ]

    mode = forms.ChoiceField(
        choices=MODE_CHOICES,
        initial=StockMovement.MovementType.IN,
        widget=forms.RadioSelect,
        label="Operation",
    )
    quantity = forms.IntegerField(
        min_value=0,
        label="Quantity",
    )
    reason = forms.CharField(
        max_length=200, required=False,
        label="Reason",
        widget=forms.TextInput(attrs={
            "placeholder": "e.g. Purchase order, damaged in transit",
        }),
    )
    reference = forms.CharField(
        max_length=100, required=False,
        label="Reference",
        help_text="PO number, invoice number, etc.",
    )