# Generated by Django 6.1.1 on 2026-10-09 14:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('medicine', 'Medicine'), ('otc', 'Over-the-counter'), ('consumable', 'Consumable / Dressing'), ('food', 'Food & Provisions'), ('cosmetic', 'Cosmetics / Toiletries'), ('device', 'Medical Device'), ('other', 'Other')], default='medicine', help_text='What type of product belongs here.', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_controlled', models.BooleanField(default=False, help_text='Controlled drugs (narcotics, psychotropics) — stricter POS logging.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='accounts.business')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, help_text='Auto-generated if left blank.', max_length=50)),
                ('barcode', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(help_text='Brand name (medicines) or product name (non-medicines).', max_length=200)),
                ('strength', models.CharField(blank=True, help_text="Dosage strength, e.g. '500 mg'.", max_length=50)),
                ('form', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('suspension', 'Suspension'), ('injection', 'Injection'), ('cream', 'Cream'), ('ointment', 'Ointment'), ('drops', 'Drops'), ('inhaler', 'Inhaler'), ('suppository', 'Suppository'), ('sachet', 'Sachet'), ('piece', 'Piece'), ('pack', 'Pack'), ('bottle', 'Bottle'), ('tin', 'Tin'), ('bag', 'Bag'), ('box', 'Box'), ('other', 'Other')], default='tablet', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, help_text='Cost per selling unit, in Leones.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Retail price per selling unit, in Leones.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('pack_size', models.PositiveIntegerField(default=1, help_text='Selling units per pack (e.g. 10 tablets per strip).')),
                ('unit', models.CharField(default='tablet', help_text='Selling unit: tablet, ml, piece, tin, etc.', max_length=20)),
                ('is_prescription', models.BooleanField(default=False, help_text='Prescription-only (Rx) medicine.')),
                ('is_controlled', models.BooleanField(default=False, help_text='Controlled substance — extra logging at POS.')),
                ('is_medicine', models.BooleanField(default=True, help_text='Uncheck for food stuffs, cosmetics, provisions, etc.')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Current on-hand quantity in selling units.')),
                ('reorder_level', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Leave blank if the product does not expire.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.business')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Received'), ('out', 'Dispensed'), ('adjust', 'Adjustment'), ('expired', 'Expired / Disposed'), ('return', 'Return to supplier')], max_length=10)),
                ('quantity', models.IntegerField(help_text='Positive = increase, negative = decrease.')),
                ('quantity_before', models.IntegerField(default=0)),
                ('quantity_after', models.IntegerField(default=0)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('reference', models.CharField(blank=True, help_text='Sale ref, PO number, prescription ID, etc.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='accounts.business')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('license_number', models.CharField(blank=True, help_text='PBSL wholesaler / distributor licence number.', max_length=50)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='accounts.business')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.supplier'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['business', 'name'], name='inventory_c_busines_2c9b0c_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('business', 'name'), name='unique_category_name_per_business'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['business', '-created_at'], name='inventory_s_busines_f753d1_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product', '-created_at'], name='inventory_s_product_cfb4fb_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['business', 'movement_type'], name='inventory_s_busines_a51983_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['business', 'name'], name='inventory_s_busines_d103e7_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['business', 'is_active'], name='inventory_s_busines_47c58a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['business', 'name'], name='inventory_p_busines_c181c4_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['business', 'sku'], name='inventory_p_busines_21859e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['business', 'barcode'], name='inventory_p_busines_23b9b6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['business', 'is_active'], name='inventory_p_busines_dc2763_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['business', 'is_medicine'], name='inventory_p_busines_0491ea_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['business', 'expiry_date'], name='inventory_p_busines_d7f515_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('business', 'sku'), name='unique_sku_per_business'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode__isnull', False), models.Q(('barcode', ''), _negated=True)), fields=('business', 'barcode'), name='unique_barcode_per_business'),
        ),
    ]
